spring:
  application:
    name: groceries
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:groceries}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
          ddl-auto: validate